version: '3.8'
services:
  bsm:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 2
      resources:
        limits:
          cpus: "1"
          memory: '200M'
    image: puntung/rokok:latest
    dns:
      - 1.1.1.1
      - 8.8.8.8
    logging: 
      driver: "local"
      options:
        max-size: "1m"
    volumes:
      - ./proxychains4.conf:/root/proxychains4.conf
